############################
## HUGO MODULES
## Install or uninstall themes and plugins here.
## Docs: https://gohugo.io/hugo-modules/
############################

proxy: https://goproxy.cn

imports:
  - path: github.com/HugoBlox/hugo-blox-builder/modules/blox-plugin-netlify
  - path: github.com/HugoBlox/hugo-blox-builder/modules/blox-plugin-reveal
  - path: github.com/HugoBlox/hugo-blox-builder/modules/blox-bootstrap/v5
